#!/usr/bin/env node
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');
const source = fs.readFileSync(path.join(__dirname, '..', 'ErgoModel.qml'), 'utf8');
const check = {running: false};
const apply = {running: false};
const root = {lowLatencyHelperAvailable: false, lowLatencyBusy: false, lowLatencyFailed: true, bluetoothAdapter: 'hci0', lowLatencyScript: '/plugin/scripts/low-latency.sh'};
const context = vm.createContext({root, lowLatencyCheck: check, lowLatencyApply: apply, Qt: {callLater: fn => fn()}});
for (const name of ['checkLowLatency', 'runLowLatency']) {
  const fn = source.match(new RegExp('^  function ' + name + '\\([^]*?^  \\}', 'm'));
  assert.ok(fn);
  vm.runInContext(fn[0], context);
  root[name] = context[name];
}
const handler = source.match(/property Process lowLatencyCheck: Process \{[\s\S]*?onStreamFinished: \{([\s\S]*?)^      \}/m);
vm.runInContext('function deliver(text) {' + handler[1] + '}', context);
root.checkLowLatency();
assert.equal(root.lowLatencyFailed, false, 'Opening panel retries a previous authorization failure');
assert.deepEqual(Array.from(check.command), ['/plugin/scripts/low-latency.sh', '--status', 'hci0']);
context.deliver('{"version":1,"helperAvailable":true,"canRestore":true,"configured":true,"state":"partial"}');
assert.equal(root.lowLatencyState, 'partial');
assert.equal(root.lowLatencyConfigured, true);
root.bluetoothAdapter = 'hci1';
context.deliver('{"version":1,"helperAvailable":true,"canRestore":true,"configured":false,"state":"applied"}');
assert.equal(root.lowLatencyState, 'partial', 'Ignore response for previous adapter');
check.running = false;
root.lowLatencyFailed = true;
root.checkLowLatency(true);
context.deliver('{"version":1,"helperAvailable":true,"canRestore":true,"configured":true,"state":"unknown"}');
assert.equal(root.lowLatencyState, 'unknown', 'Keep profile state separate from authorization failure');
assert.equal(root.lowLatencyFailed, true);
check.running = false;
root.checkLowLatency();
context.deliver('{"version":1,"helperAvailable":true,"canRestore":true,"configured":true,"state":"unknown"}');
assert.equal(root.lowLatencyState, 'unknown', 'Fresh read is not permanently masked by old failure');
root.runLowLatency('--enable');
assert.equal(apply.running, true);
assert.deepEqual(Array.from(apply.command), ['/plugin/scripts/low-latency.sh', '--enable', 'hci1']);
root.lowLatencyBusy = true;
root.runLowLatency('--disable');
assert.equal(apply.command[1], '--enable', 'Do not start competing privileged operations');
root.lowLatencyBusy = false;
root.lowLatencyHelperAvailable = false;
apply.running = false;
root.runLowLatency('--enable');
assert.equal(apply.running, false, 'Never elevate without a trusted installed helper');
root.lowLatencyHelperAvailable = true;
root.runLowLatency('--reapply');
assert.equal(apply.running, false, 'Internal administrative actions are not exposed through the plugin');
root.bluetoothAdapter = '';
root.runLowLatency('--enable');
assert.equal(apply.running, false);
root.runLowLatency('--disable');
assert.deepEqual(Array.from(apply.command), ['/plugin/scripts/low-latency.sh', '--disable', '-']);
root.runLowLatency('--remove-legacy');
assert.equal(apply.command[1], '--remove-legacy');
console.log('PASS: Production controller model: status, late responses, authorization error recovery, busy guard.');
